# Generated by Django 4.2.17 on 2025-12-30 02:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('christmas', '0009_recipe_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dn7apsma3/image/upload/v1234567890/placeholder.png', max_length=255, verbose_name='image'),
        ),
    ]
